# Generated by Django 2.2.8 on 2020-05-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200508_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('SL', 'Slipper'), ('SH', 'Sport Wear'), ('OW', 'Outwear')], max_length=10),
        ),
    ]
