# Generated by Django 2.2.8 on 2020-05-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200512_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='item',
        ),
        migrations.AddField(
            model_name='size',
            name='item',
            field=models.ManyToManyField(to='core.Item'),
        ),
    ]
