# Generated by Django 2.2.8 on 2020-05-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20200512_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='item',
            field=models.ManyToManyField(to='core.Size'),
        ),
    ]
