# Generated by Django 2.2.8 on 2020-05-12 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20200512_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item',
            new_name='size',
        ),
    ]
