# Generated by Django 2.2.8 on 2020-05-12 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20200512_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='core.Item'),
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
    ]
