# Generated by Django 2.2.8 on 2020-05-12 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20200512_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='core.Attribute'),
        ),
    ]
