# Generated by Django 2.2.8 on 2020-05-12 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20200512_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Item'),
        ),
    ]
