# Generated by Django 2.2.8 on 2020-05-12 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20200512_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='core.Item'),
        ),
    ]
