# Generated by Django 2.2.8 on 2020-05-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20200513_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
