# Generated by Django 2.2.4 on 2020-05-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20200517_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='landmarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
