# Generated by Django 2.2.4 on 2020-05-17 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20200517_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_address',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
    ]
